name: LibraDesigner
favicon: null
layout_spectrum: 0.50658
typography_spectrum: 0.84414
title: Libra Designer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ff0000'
    - '#00ffff'
    - '#ffff00'
    - '#0076bf'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
