name: LibraDesigner
favicon: null
layout_spectrum: 0.5607630352023989
typography_spectrum: 0.7947749739978462
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9755293177440763
  lightness: 0.9881415381096303
  saturation: 0.34703280008397996
  rhythmicContrast: 0.566402894211933
purpose: []
